//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeitApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BalancedDietEntities : DbContext
    {
        public BalancedDietEntities()
            : base("name=BalancedDietEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RestProducts> RestProducts { get; set; }
        public virtual DbSet<SuggestionProducts> SuggestionProducts { get; set; }
        public virtual DbSet<UserBLProducts> UserBLProducts { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserWLProducts> UserWLProducts { get; set; }
        public virtual DbSet<DietProducts> DietProducts { get; set; }
        public virtual DbSet<UsersAuth> UsersAuth { get; set; }
    }
}
