//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeitApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietProducts
    {
        public DietProducts() { }
        public DietProducts(Guid userId, Guid productId, string name, int cals, float prots, float fats, float carbons, float mass, string category, DateTime date, int day)
        {
            this.id = Guid.NewGuid();
            this.UserId = userId;
            this.ProductId = productId;
            this.Name = name;
            this.Calories = cals;
            this.Proteins = prots;
            this.Fats = fats;
            this.Carbons = carbons;
            this.Mass = mass;
            this.Category = category;
            this.Date = date;
            this.DayNumber = day;
        }
        public System.Guid id { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ProductId { get; set; }
        public Nullable<System.Guid> UserProductId { get; set; } = null;
        public string Name { get; set; }
        public int Calories { get; set; }
        public float Proteins { get; set; }
        public float Fats { get; set; }
        public float Carbons { get; set; }
        public float Mass { get; set; }
        public string Category { get; set; }
        public System.DateTime Date { get; set; }
        public int DayNumber { get; set; }
    }
}
