//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeitApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public System.Guid id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int Sex { get; set; }
        public int Weight { get; set; }
        public int Height { get; set; }
        public float Activity { get; set; }
        public int DietGoal { get; set; }
    }
}
