//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeitApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWLProducts
    {
        public System.Guid id { get; set; }
        public System.Guid UserId { get; set; }
        public string Name { get; set; }
        public int Calories { get; set; }
        public float Proteins { get; set; }
        public float Fats { get; set; }
        public float Carbons { get; set; }
        public string Category { get; set; }
    }
}
